spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/expDB?createDatabaseIfNotExist=true
    username: root
    password: root
    tomcat:
      max-active: 20
      max-idle: 5
      min-idle: 1
      initial-size: 5
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 30000
      testOnBorrow: true
      validation-query: SELECT 1 FROM DUAL
      remove-abandoned: true
      remove-abandoned-timeout: 60
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      minimum-idle: 5
      max-lifetime: 600000
      #max-lifetime should be several seconds shorter than any database or infrastructure imposed connection time limit
      idle-timeout: 10000
      #idle-timeout setting only applies when minimum-idle is defined to be less than maximum-pool-size
      #a value of 0 means that idle connections are never removed from the pool
      #a connection will never be retired as idle before given timeout
      #maximum amount of time that a connection is allowed to sit idle in the pool
      leak-detection-threshold: 10000
      #amount of time that a connection can be out of the pool before a message is logged indicating a possible connection leak
      #value of 0 means leak detection is disabled
      #lowest acceptable value for enabling leak detection is 2000 (2 seconds)
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: false
    properties.hibernate.use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQL5Dialect


server:
  port: 9898


logging:
  level:
    root: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.zaxxer.hikari.pool.*: DEBUG
    com.zaxxer.hikari.HikariConfig: OFF
    o.h.r.j.i.ResourceRegistryStandardImpl: OFF
    o.s.orm.jpa.JpaTransactionManager: OFF
    org.hibernate.internal.SessionImpl: OFF



#server.port=9898
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/data-exp?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.sql.init.mode=never
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
#logging.level.org.hibernate.SQL=ERROR