spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data-exp?createDatabaseIfNotExist=true
    username: root
    password:
    tomcat:
      max-active: 20
      max-idle: 5
      min-idle: 1
      initial-size: 5
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 30000
      testOnBorrow: true
      validation-query: SELECT 1 FROM DUAL
      remove-abandoned: true
      remove-abandoned-timeout: 60
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 10000
      idle-timeout: 8000
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: false
    properties.hibernate.use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQL5Dialect


server:
  port: 9898


logging:
  level:
    root: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.apache.kafka.clients.producer: WARN
    org.apache.kafka.clients.consumer: WARN
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.zaxxer.hikari.pool: DEBUG
    com.zaxxer.hikari.pool.*: DEBUG
    com.zaxxer.hikari.HikariConfig: OFF
    o.h.r.j.i.ResourceRegistryStandardImpl: OFF
    o.s.orm.jpa.JpaTransactionManager: OFF
    org.hibernate.internal.SessionImpl: OFF



#server.port=9898
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/data-exp?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.sql.init.mode=never
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
#logging.level.org.hibernate.SQL=ERROR